FROM gradle:8.5-jdk17 AS build
WORKDIR /app
COPY settings.gradle .
COPY stockInterface/ ./stockInterface/
COPY stockClient/    ./stockClient/
RUN gradle :stockInterface:build -x test --no-daemon
RUN gradle :stockClient:build    -x test --no-daemon
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/stockClient/build/libs/stockClient-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
