spring.application.name=stockClient
server.port=8080
stockServerURL=http://stock-server-service:8081/health
grpc.client.stockService.address=static://stock-server-service:9090
grpc.client.stockService.negotiation-type=plaintext
